/*
Built using Kango - Cross Browser Extensions framework.
http://kangoextensions.com/
*/
var kango=null;function KangoMessageServer(){var a=this;this._eventListener=new KangoEventListener;window.addEventListener("message",function(b){a._onMessage(b)},!1)}
KangoMessageServer.prototype={_eventListener:null,_onMessage:function(a){var b=JSON.parse(a.data);if(b.source=="client"){var d={data:b.data,sendResponse:function(c){a.source.postMessage(JSON.stringify({name:b.name,id:b.id,data:c,source:"server"}),"*")}};if(b.name=="invoke"){var c=KangoInvoke(b.data.method,b.data.params);d.sendResponse({result:c})}else KangoPopupMessageClient.postMessage(b.name,b.data,function(a){d.sendResponse(a)})}},addListener:function(a,b){return this._eventListener.addEventListener(a,
b)}};function KangoMessageClient(){}KangoMessageClient.prototype={_generateId:function(){return Math.random()},postMessage:function(a,b,d){var c=this._generateId();chrome.extension.sendRequest(JSON.stringify({name:a,id:c,data:b}),d)}};function KangoInvoke(a,b){for(var d=a.split("."),c=function(){return this}.call(null),f=d.pop(),e=0;e<d.length;e++)c=c[d[e]];return c[f].apply(c,b)}
var KangoPopupMessageServer=new KangoMessageServer,KangoPopupMessageClient=new KangoMessageClient,KangoPopup={_container:null,url:"",init:function(){KangoPopupMessageServer.addListener("invoke",function(a){var b=a.data,b=KangoInvoke(b.method,b.params);a.sendResponse({result:b})});kango=chrome.extension.getBackgroundPage().kango;this._container=document.getElementById("container");var a=kango.ui.browserButton.getPopupDetails();this.url=kango.io.getFileUrl(a.url);if(typeof a.width=="number")this._container.style.width=
a.width+"px";if(typeof a.height=="number")this._container.style.height=a.height+"px";var b=this;window.setTimeout(function(){b.createFrame()},50)},createFrame:function(){var a=document.createElement("iframe");a.width="100%";a.height="100%";a.src=this.url;this._container.appendChild(a)}};window.addEventListener("load",function(){KangoPopup.init()},!1);
